### ISSUE TITLE
Modify ColorToken to "remember" how it was initialized

### ISSUE THREAD

**Issue by rpwachowski** [DuetHealth/Gooey#46]
Right now, the internals of ColorToken only store the `[0...255]` RGB components. This is fine for a naive implementation and most use cases. For any more robust usages involving other representations, though, the current backing mechanism causes a loss of information. Take, for example, the changes staged in #45. The color white (`rgb(255, 255, 255)`) is infinite:
```swift
ColorToken(hue: .random(in: 0...1), saturation: 0, value: 1)
```
but for those more robust usages, the following is not necessarily true:
```swift
// Does not always hold.
ColorToken(hue: .random(in: 0...1), saturation: 0, value: 1) == ColorToken(hue: .random(in: 0...1), saturation: 0, value: 1)
```
The proposed solution is to introduce a private nested type for retaining the raw values used to initialize the `ColorToken` instead of always calculating the RGB components. The existing  property accessors/mutators would need modified to either calculate or just return depending on what the storage has retained.

A (perhaps) less-than-desirable consequence of pursuing this change is that equality of two colors becomes a little more complicated. Merely conforming to `Equatable` is not an option, but it is easy enough to introduce color comparers which know how to reconcile the various properties.

**Comment by powerje** [comment]
I took a stab at this in https://github.com/DuetHealth/Gooey/pull/62

I'm not sure what to do around the intensity accessor though.

**Comment by powerje** [comment]
Fixed by https://github.com/DuetHealth/Gooey/pull/62
